### ISSUE TITLE
The "search_api_index" entity type does not exist.

### ISSUE THREAD

**Issue by nigelgbanks** [Islandora-Devops/isle-site-template#66]
Issue is occurring on integration tests, can't reproduce locally, seems to be a race condition, previously described here:

https://github.com/Islandora-Devops/isle-dc/issues/392

**Comment by nigelgbanks** [comment]
https://github.com/Islandora-Devops/isle-site-template/actions/runs/10883566723/job/30197004979

**Comment by nigelgbanks** [comment]
The error actually occurs when doing a cache:rebuild:

https://github.com/Islandora-Devops/isle-site-template/actions/runs/10883717356/job/30197464465

```
drupal-dev-1  | + drush --root=/var/www/drupal --uri=https://islandora.dev/ cache:rebuild
drupal-dev-1  | 
drupal-dev-1  | In EntityTypeManager.php line 142:
drupal-dev-1  | 
drupal-dev-1  |   The "search_api_index" entity type does not exist.  
drupal-dev-1  | 
drupal-dev-1  |
```

**Comment by nigelgbanks** [comment]
Not much to go off from the actual installation as to what the true problem is.

Just two warnings. 
```
+ /usr/local/bin/install-drupal-site.sh --driver mysql --host mariadb --port 3306 --db-user drupal_default --db-password password --db-name drupal_default minimal --account-mail=webmaster@localhost.com --account-name=admin --account-pass=password --site-mail=webmaster@localhost.com --locale=en '--site-name=Islandora Digital Collections' --sites-subdir=default --existing-config
drupal-dev-1  | s6-rc: info: service fpm successfully started
drupal-dev-1  | s6-rc: info: service nginx: starting
drupal-dev-1  | Installing site.
drupal-dev-1  | 127.0.0.1 - - [16/Sep/2024:12:25:40 +0000] "GET /status HTTP/1.1" 200 381 "-" "curl/8.10.0" "-"
drupal-dev-1  | s6-rc: info: service nginx successfully started
drupal-dev-1  |  You are about to:
drupal-dev-1  |  * DROP all tables in your 'drupal_default' database.
drupal-dev-1  | 
drupal-dev-1  |  [warning] Undefined array key 1 SiteInstallCommands.php:82
drupal-dev-1  |  [warning] Undefined array key 1 SiteInstallCommands.php:82
```

**Comment by nigelgbanks** [comment]
We use drush "13.0.0-beta5" at time of writing https://github.com/Islandora-Devops/islandora-starter-site/blob/a129ed9e57b0de749f7c32f61684d639031e74ae/composer.lock#L5483

**Comment by nigelgbanks** [comment]
Line of the warning: https://github.com/drush-ops/drush/blob/8389f62c17dee1e9212c97e69410e126989f211a/src/Commands/core/SiteInstallCommands.php#L82

**Comment by nigelgbanks** [comment]
Seems like this is a red herring.

**Comment by nigelgbanks** [comment]
Comes from this new feature: https://github.com/drush-ops/drush/commit/5cb82824fc52396098ee490e8b05a5c28d626ab8

**Comment by nigelgbanks** [comment]
I'm leaning more towards an issue with the https://github.com/Islandora-Devops/islandora-starter-site, in that some module is not installing itself properly due to missing dependencies, or some such.

**Comment by nigelgbanks** [comment]
https://git.drupalcode.org/project/search_api/-/blob/8.x-1.x/src/Entity/Index.php?ref_type=heads#L32

**Comment by nigelgbanks** [comment]
More from other branches.

```
Error: Class "Drupal\search_api\Entity\Server" not found in /var/www/drupal/solr.php on line 6 #0 /var/www/drupal/vendor/drush/drush/src/Commands/core/PhpCommands.php(107): include()
#1 [internal function]: Drush\Commands\core\PhpCommands->script()
#2 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): call_user_func_array()
#3 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback()
#4 /var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter()
#5 /var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): Consolidation\AnnotatedCommand\CommandProcessor->process()
#6 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): Consolidation\AnnotatedCommand\AnnotatedCommand->execute()
#7 /var/www/drupal/vendor/symfony/console/Application.php(1096): Symfony\Component\Console\Command\Command->run()
#8 /var/www/drupal/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#9 /var/www/drupal/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#10 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): Symfony\Component\Console\Application->run()
#11 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#12 /var/www/drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#13 /var/www/drupal/vendor/drush/drush/drush(4): require('/var/www/drupal...')
#14 /var/www/drupal/vendor/bin/drush(119): include('/var/www/drupal...')
#15 {main}
Error: Class "Drupal\search_api\Entity\Server" not found in include() (line 6 of /var/www/drupal/solr.php).
```

https://github.com/Islandora-Devops/isle-site-template/pull/65

**Comment by nigelgbanks** [comment]
Ah thats from the other test after the ping.

**Comment by nigelgbanks** [comment]
Maybe will fix? https://github.com/Islandora-Devops/isle-site-template/pull/74

**Comment by nigelgbanks** [comment]
It did not

**Comment by joecorall** [comment]
Great work on https://github.com/Islandora-Devops/isle-site-template/pull/76 @nigelgbanks. Closing this.

**Comment by ajstanley** [comment]
I've been seeing the same issue building Sandbox on the Droplet.  I've had to retrigger a rebuild a few times this week.
It started happening a few days after the last update, but the failures are not consistent or predictable.

I see a lot of these in the logs
```
127.0.0.1 - - [09/Mar/2025:14:37:18 +0000] "GET /status HTTP/1.1" 200 382 "-" "curl/8.12.1" "-"
NOTICE: PHP message: Drupal\Component\Plugin\Exception\PluginNotFoundException: The "key" entity type does not exist. in /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php on line 142 #0 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php(260): Drupal\Core\Entity\EntityTypeManager->getDefinition()
#1 /var/www/drupal/web/core/lib/Drupal/Core/Entity/EntityTypeManager.php(195): Drupal\Core\Entity\EntityTypeManager->getHandler()
```
but I also see it as the first line in a successful build, so maybe not relevant.

**Comment by joecorall** [comment]
@ajstanley - i do not think the sandbox uses isle-site-template? You may want to apply the same fix Nigel implemented for isle-site-template: https://github.com/Islandora-Devops/isle-site-template/pull/76/files

I know isle-dc suffers from this same problem, and it pops up time to time in the nightly build/test in that repo. The underlying cause seems like some sort of race around Drupal's cache while doing a large amount of site config operations that are done when installing a site. The issue is solved for isle-site-template so I am closing this issue.
